modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL="https://github.com/minecraftabnormals/Personality/issues"
license = "https://github.com/minecraftabnormals/Personality/blob/main/LICENSE.txt"

[[mods]]
	modId = "personality"
	version = "${file.jarVersion}"
	displayName = "Personality"
	authors = "Jackson and Bagel"
	credits = "Tallestred (Eating Animation)"
	description = '''Adds new cosmetic features to players.'''

[[dependencies.personality]]
	modId = "forge"
	mandatory = true
	versionRange = "[32,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.personality]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.16.1]"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.environmental]]
	modId="abnormals_core"
	mandatory=true
	versionRange="[2.0.7,)"
	ordering="AFTER"
	side="BOTH"