modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/personality/issues"
license = "https://github.com/team-abnormals/personality/blob/main/LICENSE"

[[mods]]
    modId = "personality"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    itemIcon = "minecraft:oak_stairs"
    authors = "Team Abnormals"
    credits = "Jackson and bageldotjpg"
    displayName = "Personality"
    description = '''
    Gives the game more personality by adding new game-feel features and more!
    '''

[[dependencies.personality]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.personality]]
    modId = "forge"
    mandatory = true
    versionRange = "[36.1.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.personality]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.1.1,)"
    ordering = "AFTER"
    side = "BOTH"