modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/personality/issues"
license = "https://github.com/team-abnormals/personality/blob/main/LICENSE"

[[mods]]
    modId = "personality"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "Jackson and bageldotjpg"
    displayName = "Personality"
    description = '''
    Adds new features to players.
    '''

[[dependencies.personality]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.3,1.17)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.personality]]
    modId = "forge"
    mandatory = true
    versionRange = "[34.1.42,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.personality]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[3.0.1,)"
    ordering = "AFTER"
    side = "BOTH"